ACTION_SIZE: 3
BATCH_SIZE: 256
CHECKPOINT_DIR: experiments/DDPG/train/checkpoints
CHECKPOINT_EVERY: 500
COLLISION_RADIUS: 0.5
DRL_STEP_DURATION: 0.1
DRONE_VIZ_SPAN_CELLS: 10
EPISODE_TIMEOUT: 90.0
EVAL_DIR: experiments/DDPG/eval
EVAL_GOALS_DIR: dataset/maps_eval/simple_goals
EVAL_MAPS_DIR: dataset/maps_eval/simple
EXPERIMENT_DIR: experiments/DDPG
EXPERIMENT_NAME: DDPG
EXPERIMENT_TYPE: DDPG
FREE: 255
GAMMA: 0.99
GOAL_THRESHOLD: 1.0
GRADIENT_STEPS_PER_EPISODE: 2
HIDDEN_SIZE: 512
HOVER_ALTITUDE: -1.0
LOAD_MODEL: false
LOG_STD_MAX: 2
LOG_STD_MIN: -20
LR: 0.001
MAP_CELL_SIZE: 0.25
MAP_PIXELS: 250
MAP_SIDE_M: 62.25
MAX_EPISODE_STEP: 900
MAX_GOAL_DISTANCE: 88.03479425772517
MINIMUM_BUFFER_SIZE: 25000
NUM_CRITICS: 3
NUM_GPU: 0
NUM_META_AGENT: 8
NUM_SCAN_SAMPLES: 40
OBSTACLE_PENALTY: -20.0
OBSTACLE_PENALTY_THRESHOLD: 1.0
OCCUPIED: 1
OU_NOISE_DECAY_EPISODES: 3000
OU_NOISE_MAX_SIGMA: 0.2
OU_NOISE_MIN_SIGMA: 0.05
PER_ALPHA: 0.6
PER_BETA_FRAMES: 6000
PER_BETA_START: 0.4
PER_EPSILON: 1.0e-06
PHYSICS_TS: 0.005
POLICY_UPDATE_FREQUENCY: 1
REPLAY_SIZE: 500000
REWARD_CRASH: -2000.0
REWARD_SUCCESS: 2500.0
REWARD_TIMEOUT: -100.0
SAVE_IMG_GAP: 500
SENSOR_RANGE: 12.0
SPEED_ANGULAR_MAX: 1.0471975511965976
SPEED_LINEAR_MAX: 3.0
SPEED_LINEAR_Y_MAX: 1.5
STATE_SIZE: 45
SUMMARY_WINDOW: 10
TAU: 0.001
TENSORBOARD_DIR: experiments/DDPG/train/tensorboard
TRAIN_GOALS_DIR: dataset/maps_train/simple_goals
TRAIN_MAPS_DIR: dataset/maps_train/simple
TRAIN_PLOTS_DIR: experiments/DDPG/train/plots
UNKNOWN: 127
USE_GPU: false
USE_GPU_GLOBAL: true
USE_MULTI_CRITIC: false
USE_PER: false
WANDB_ENABLED: true
WANDB_ENTITY: null
WANDB_PROJECT: DRL-NAV
